---
- name: Deploy on k8s
  hosts: 10.128.0.3
  become: true
  tasks: 
     - name: create new deployment
       command: kubectl create -f /home/devops/Deployment.yml
     - name: create new service
       command: kubectl create -f /home/devops/Service.yml
