kind: Deployment
apiVersion: apps/v1
metadata:
   name: bangalore-city
spec:
   replicas: 3
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: bangalore-devops
   template:
      metadata:
        labels:
          app: bangalore-devops
      spec:
       containers:
        - name: bangalore-devops
          image: arjunvv0108/pipeline-demo:Latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
